### ISSUE TITLE
Why ImmutableList of size 7 occupies 128 bytes?

### ISSUE THREAD

**Issue by wzslr321** [benbjohnson/immutable#42]
List below contains 7 elements, but when I inspect it with debugger it resizes to length of 32, filling the rest with empty strings. I'm curious, what is the reason for that? I understand that resizing is expensive, but it seems like a little bit too much at first glance.
```go
list := immutable.NewList[string](
	"one",
	 "two",
	"three",
	"four",
	"five",
	"six",
	"seven",
)
```
![image](https://user-images.githubusercontent.com/59893892/218270176-deefa277-82b9-47cd-930f-57958f19b35a.png)

![image](https://user-images.githubusercontent.com/59893892/218270137-dfddb8fd-45a8-443d-842e-ec6ece03b3ea.png)

**Comment by benbjohnson** [comment]
This library is a port of `immutable.js` so I'm not sure what they're reasoning was for 32 specifically. IIRC the number needs to be a power of two so maybe it could be dropped down to 16 and that would make more sense.

It really only matters if you have a lot of small lists. In my experience, it's more common to see one or a few large immutable collections being shared rather than lots of small ones.

**Comment by wzslr321** [comment]
Thanks for the answer :)
